# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x06orders\"\x8d\x01\n\x0cOrderRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0b\n\x03qty\x18\x02 \x01(\t\x12\x0c\n\x04side\x18\x03 \x01(\t\x12\x12\n\norder_type\x18\x04 \x01(\t\x12\x15\n\rtime_in_force\x18\x05 \x01(\t\x12\x13\n\x0blimit_price\x18\x06 \x01(\t\x12\x12\n\nstop_price\x18\x07 \x01(\t\"\x97\x01\n\rOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x0b\n\x03qty\x18\x05 \x01(\t\x12\x0c\n\x04side\x18\x06 \x01(\t\x12\x12\n\nfilled_qty\x18\x07 \x01(\t\x12\x14\n\x0corder_status\x18\x08 \x01(\tB%Z#trading-desk/internal/protos/ordersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#trading-desk/internal/protos/orders'
  _globals['_ORDERREQUEST']._serialized_start=24
  _globals['_ORDERREQUEST']._serialized_end=165
  _globals['_ORDERRESPONSE']._serialized_start=168
  _globals['_ORDERRESPONSE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
